name: Deploy to AWS with OIDC

on:
  push:
    branches:
      - main 
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build with Maven (quiet)
      run: mvn clean package -q \
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      working-directory: ./lambda

    - name: Save Maven cache
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Python dependencies and AWS CDK
      run: |
        python -m pip install --upgrade pip
        npm install -g aws-cdk

    - name: Deploy to AWS Lambda with CDK
      run: cdk deploy \
        -c domainName="${{ secrets.DOMAIN_NAME }}" \
        -c subdomainName="${{ secrets.SUBDOMAIN_NAME }}" \
        -c calendarName="${{ secrets.CALENDAR_NAME }}" \
        -c icsUrls="${{ secrets.ICS_URLS }}"
      working-directory: ./cdk
