name: Deploy to AWS with OIDC

on:
  push:
    branches:
      - main 
      - aws

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./lambda

    - name: Configure AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS Lambda
      run: cdk deploy -c domainName="${{ secrets.DOMAIN_NAME }}" -c subdomainName="${{ secrets.SUBDOMAIN_NAME }}" -c calendarName="${{ secrets.CALENDAR_NAME }}" -c icsUrls="${{ secrets.ICS_URLS }}"
